version: "1.0"

services:
  aipe:
    image: rekpero/aipe-official:latest
    expose:
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - SERPER_API_KEY=
profiles:
  name: aipe-official
  duration: 1h
  tier:
    - community
  compute:
    aipe:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        aipe:
          denom: USDT
          amount: 60000000

deployment:
  aipe:
    westcoast:
      profile: aipe
      count: 1
